# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a075feb52c93fc43906e61928aa6013029779ad46f129684ba0e73a54727ddb36b4daa3eb67e00696c8eb09dc8945116d657628e3ced6db586d21531ff784498

test:
  secret_key_base: 6b1eac4000a415558bcb8e2f0ac7b7167b6a645d2dc0307ff51b272dfd94b91096876567d4d30840a1f08b9a0d5a4b5938eb8d05a4322f99af66a3f831b4e27c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
